name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "30 6 * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          pyproject-file: "fabicrawler/pyproject.toml"
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "fabicrawler/.python-version"
      - name: Fetch latest data
        working-directory: ./fabicrawler
        run: |-
          uv run -- scrapy crawl fabi-muenchen -O ../website/static/courses.json
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
